/***
 * 診断の質問リスト
 * @type {[{subTitle: string, answer: number, description: string, colorCode: string, id: number, title: string, choices: string[][], faultCount: number}]}
 */
export const secondExam = [
    {
        id:1,
        title:"鴇色",
        subTitle:"明るい紫みの赤",
        colorCode:"#f4b3c2",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"鴇色",
                    "colorCode":"#f4b3c2"
                },
                {
                    "name":"オールドローズ",
                    "colorCode":"#da8d93"
                },
                {
                    "name":"ローズピンク",
                    "colorCode":"#f29c9f"
                }
            ],
            [
                {
                    "name":"鴇色",
                    "colorCode":"#f4b3c2"
                },
                {
                    "name":"桜色",
                    "colorCode":"#fdeeef"
                },
                {
                    "name":"珊瑚色",
                    "colorCode":"#F3ADA3"
                }
            ],
            [
                {
                    "name":"鴇色",
                    "colorCode":"#f4b3c2"
                },
                {
                    "name":"韓紅色",
                    "colorCode":"#e95464"
                },
                {
                    "name":"紅梅色",
                    "colorCode":"#f3a7a5"
                }
            ]
        ],
        answer:1,
    },
    {
        id:2,
        title:"韓紅色",
        subTitle:"あざやかな赤",
        colorCode:"#e95464",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"紅梅色",
                    "colorCode":"#f3a7a5"
                },
                {
                    "name":"カーマイン",
                    "colorCode":"#d7003a"
                },
                {
                    "name":"韓紅色",
                    "colorCode":"#e95464"
                }
            ],
            [
                {
                    "name":"ポピーレッド",
                    "colorCode":"#e9474d"
                },
                {
                    "name":"オールドローズ",
                    "colorCode":"#da8d93"
                },
                {
                    "name":"韓紅色",
                    "colorCode":"#e95464"
                }
            ],
            [
                {
                    "name":"カーマイン",
                    "colorCode":"#d7003a"
                },
                {
                    "name":"ポピーレッド",
                    "colorCode":"#e9474d"
                },
                {
                    "name":"韓紅色",
                    "colorCode":"#e95464"
                }
            ]
        ],
        answer:3,
    },
    {
        id:3,
        title:"蘇芳",
        subTitle:"くすんだ赤",
        colorCode:"#9e3d3e",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"弁柄色",
                    "colorCode":"#8f2d12"
                },
                {
                    "name":"鳶色",
                    "colorCode":"#8b4239"
                },
                {
                    "name":"蘇芳",
                    "colorCode":"#9e3d3e"
                }
            ],
            [
                {
                    "name":"海老茶",
                    "colorCode":"#814336"
                },
                {
                    "name":"煉瓦色",
                    "colorCode":"#a2482b"
                },
                {
                    "name":"蘇芳",
                    "colorCode":"#9e3d3e"
                }
            ],
            [
                {
                    "name":"鳶色",
                    "colorCode":"#8b4239"
                },
                {
                    "name":"海老茶",
                    "colorCode":"#814336"
                },
                {
                    "name":"蘇芳",
                    "colorCode":"#9e3d3e"
                }
            ]
        ],
        answer:3,
    },
    {
        id:4,
        title:"鳶色",
        subTitle:"暗い黄みの赤",
        colorCode:"#8b4239",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"煉瓦色",
                    "colorCode":"#a2482b"
                },
                {
                    "name":"鳶色",
                    "colorCode":"#8b4239"
                },
                {
                    "name":"栗色",
                    "colorCode":"#762e05"
                }
            ],
            [
                {
                    "name":"海老茶",
                    "colorCode":"#814336"
                },
                {
                    "name":"鳶色",
                    "colorCode":"#8b4239"
                },
                {
                    "name":"チョコレート",
                    "colorCode":"#612c16"
                }
            ],
            [
                {
                    "name":"弁柄色",
                    "colorCode":"#8f2d12"
                },
                {
                    "name":"鳶色",
                    "colorCode":"#8b4239"
                },
                {
                    "name":"蘇芳",
                    "colorCode":"#9e3d3e"
                }
            ]
        ],
        answer:1,
    },
    {
        id:5,
        title:"弁柄色",
        subTitle:"暗い黄みの赤",
        colorCode:"#8f2d12",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"弁柄色",
                    "colorCode":"#8f2d12"
                },
                {
                    "name":"チョコレート",
                    "colorCode":"#612c16"
                },
                {
                    "name":"海老茶",
                    "colorCode":"#814336"
                }
            ],
            [
                {
                    "name":"弁柄色",
                    "colorCode":"#8f2d12"
                },
                {
                    "name":"蘇芳",
                    "colorCode":"#9e3d3e"
                },
                {
                    "name":"鳶色",
                    "colorCode":"#8b4239"
                }
            ],
            [
                {
                    "name":"弁柄色",
                    "colorCode":"#8f2d12"
                },
                {
                    "name":"海老茶",
                    "colorCode":"#814336"
                },
                {
                    "name":"煉瓦色",
                    "colorCode":"#a2482b"
                }
            ]
        ],
        answer:1,
    },
    {
        id:6,
        title:"海老茶",
        subTitle:"暗い黄みの赤",
        colorCode:"#814336",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"煉瓦色",
                    "colorCode":"#a2482b"
                },
                {
                    "name":"弁柄色",
                    "colorCode":"#8f2d12"
                },
                {
                    "name":"海老茶",
                    "colorCode":"#814336"
                }
            ],
            [
                {
                    "name":"栗色",
                    "colorCode":"#762e05"
                },
                {
                    "name":"鳶色",
                    "colorCode":"#8b4239"
                },
                {
                    "name":"海老茶",
                    "colorCode":"#814336"
                }
            ],
            [
                {
                    "name":"蘇芳",
                    "colorCode":"#9e3d3e"
                },
                {
                    "name":"チョコレート",
                    "colorCode":"#612c16"
                },
                {
                    "name":"海老茶",
                    "colorCode":"#814336"
                }
            ]
        ],
        answer:3,
    },
    {
        id:7,
        title:"オールドローズ",
        subTitle:"やわらかい赤",
        colorCode:"#da8d93",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"オールドローズ",
                    "colorCode":"#da8d93"
                },
                {
                    "name":"蘇芳",
                    "colorCode":"#9e3d3e"
                },
                {
                    "name":"ローズピンク",
                    "colorCode":"#f29c9f"
                }
            ],
            [
                {
                    "name":"オールドローズ",
                    "colorCode":"#da8d93"
                },
                {
                    "name":"韓紅色",
                    "colorCode":"#e95464"
                },
                {
                    "name":"紅梅色",
                    "colorCode":"#f3a7a5"
                }
            ],
            [
                {
                    "name":"オールドローズ",
                    "colorCode":"#da8d93"
                },
                {
                    "name":"紅梅色",
                    "colorCode":"#f3a7a5"
                },
                {
                    "name":"ローズピンク",
                    "colorCode":"#f29c9f"
                }
            ]
        ],
        answer:1,
    },
    {
        id:8,
        title:"ポピーレッド",
        subTitle:"あざやかな赤",
        colorCode:"#e9474d",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"韓紅色",
                    "colorCode":"#e95464"
                },
                {
                    "name":"ポピーレッド",
                    "colorCode":"#e9474d"
                },
                {
                    "name":"カーマイン",
                    "colorCode":"#d7003a"
                },
            ],
            [
                {
                    "name":"鴇色",
                    "colorCode":"#"
                },
                {
                    "name":"ポピーレッド",
                    "colorCode":"#e9474d"
                },
                {
                    "name":"紅梅色",
                    "colorCode":"#f3a7a5"
                }
            ],
            [
                {
                    "name":"カーマイン",
                    "colorCode":"#d7003a"
                },
                {
                    "name":"ポピーレッド",
                    "colorCode":"#e9474d"
                },
                {
                    "name":"蘇芳",
                    "colorCode":"#9e3d3e"
                }
            ]
        ],
        answer:2,
    },
    {
        id:9,
        title:"マルーン",
        subTitle:"暗い赤",
        colorCode:"#6a1816",
        description:"マルーン（Maroon）とはスペイン産の大粒の西洋栗のことです。",
        choices:[
            [
                {
                    "name":"蘇芳",
                    "colorCode":"#9e3d3e"
                },
                {
                    "name":"チョコレート",
                    "colorCode":"#612c16"
                },
                {
                    "name":"マルーン",
                    "colorCode":"#6a1816"
                }
            ],
            [
                {
                    "name":"海老茶",
                    "colorCode":"#814336"
                },
                {
                    "name":"バーガンディー",
                    "colorCode":"#561620"
                },
                {
                    "name":"マルーン",
                    "colorCode":"#6a1816"
                }
            ],
            [
                {
                    "name":"テラコッタ",
                    "colorCode":"#be6d55"
                },
                {
                    "name":"桧皮色",
                    "colorCode":"#965036"
                },
                {
                    "name":"マルーン",
                    "colorCode":"#6a1816"
                }
            ]
        ],
        answer:3,
    },
    {
        id:10,
        title:"テラコッタ",
        subTitle:"くすんだ黄みの赤",
        colorCode:"#be6d55",
        description:"テラコッタ（Terracotta）とはイタリア語で「焼いた（cotta）土（terra）」という意味です。",
        choices:[
            [
                {
                    "name":"テラコッタ",
                    "colorCode":"#be6d55"
                },
                {
                    "name":"バーガンディー",
                    "colorCode":"#561620"
                },
                {
                    "name":"桧皮色",
                    "colorCode":"#965036"
                }
            ],
            [
                {
                    "name":"テラコッタ",
                    "colorCode":"#be6d55"
                },
                {
                    "name":"琥珀色",
                    "colorCode":"#bf7834"
                },
                {
                    "name":"代赭",
                    "colorCode":"#bb541f"
                }
            ],
            [
                {
                    "name":"テラコッタ",
                    "colorCode":"#be6d55"
                },
                {
                    "name":"タン",
                    "colorCode":"#c1813f"
                },
                {
                    "name":"ローシェンナ",
                    "colorCode":"#d98032"
                }
            ]
        ],
        answer:1,
    },
    {
        id:11,
        title:"黄丹",
        subTitle:"つよい黄赤",
        colorCode:"#ee7948",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"柑子色",
                    "colorCode":"#f6ad48"
                },
                {
                    "name":"黄丹",
                    "colorCode":"#ee7948"
                },
                {
                    "name":"黄蘗色",
                    "colorCode":"#fef263"
                }
            ],
            [
                {
                    "name":"ゴールデンイエロー",
                    "colorCode":"#f8b856"
                },
                {
                    "name":"黄丹",
                    "colorCode":"#ee7948"
                },
                {
                    "name":"バーミリオン",
                    "colorCode":"#eb613b"
                }
            ],
            [
                {
                    "name":"マリーゴールド",
                    "colorCode":"#f39800"
                },
                {
                    "name":"黄丹",
                    "colorCode":"#ee7948"
                },
                {
                    "name":"柑子色",
                    "colorCode":"#f6ad48"
                }
            ]
        ],
        answer:2,
    },
    {
        id:12,
        title:"桧皮色",
        subTitle:"暗い灰みの黄赤",
        colorCode:"#965036",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"桧皮色",
                    "colorCode":"#965036"
                },
                {
                    "name":"代赭",
                    "colorCode":"#bb541f"
                },
                {
                    "name":"バーントシェンナ",
                    "colorCode":"#b25532"
                }
            ],
            [
                {
                    "name":"桧皮色",
                    "colorCode":"#965036"
                },
                {
                    "name":"蘇芳",
                    "colorCode":"#9e3d3e"
                },
                {
                    "name":"マルーン",
                    "colorCode":"#6a1816"
                }
            ],
            [
                {
                    "name":"桧皮色",
                    "colorCode":"#965036"
                },
                {
                    "name":"ローシェンナ",
                    "colorCode":"#d98032"
                },
                {
                    "name":"バーントシェンナ",
                    "colorCode":"#b25532"
                }
            ]
        ],
        answer:1,
    },
    {
        id:13,
        title:"代赭",
        subTitle:"くすんだ黄赤",
        colorCode:"#bb541f",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"ローシェンナ",
                    "colorCode":"#d98032"
                },
                {
                    "name":"タン",
                    "colorCode":"#c1813f"
                },
                {
                    "name":"代赭",
                    "colorCode":"#bb541f"
                }
            ],
            [
                {
                    "name":"琥珀色",
                    "colorCode":"#bf7834"
                },
                {
                    "name":"桧皮色",
                    "colorCode":"#965036"
                },
                {
                    "name":"代赭",
                    "colorCode":"#bb541f"
                }
            ],
            [
                {
                    "name":"蘇芳",
                    "colorCode":"#9e3d3e"
                },
                {
                    "name":"タン",
                    "colorCode":"#c1813f"
                },
                {
                    "name":"代赭",
                    "colorCode":"#bb541f"
                }
            ]
        ],
        answer:3,
    },
    {
        id:14,
        title:"柑子色",
        subTitle:"明るい黄赤",
        colorCode:"#f6ad48",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"マリーゴールド",
                    "colorCode":"#f39800"
                },
                {
                    "name":"黄丹",
                    "colorCode":"#ee7948"
                },
                {
                    "name":"柑子色",
                    "colorCode":"#f6ad48"
                }
            ],
            [
                {
                    "name":"黄丹",
                    "colorCode":"#ee7948"
                },
                {
                    "name":"黄蘗色",
                    "colorCode":"#fef263"
                },
                {
                    "name":"柑子色",
                    "colorCode":"#f6ad48"
                }
            ],
            [
                {
                    "name":"黄蘗色",
                    "colorCode":"#fef263"
                },
                {
                    "name":"マリーゴールド",
                    "colorCode":"#f39800"
                },
                {
                    "name":"柑子色",
                    "colorCode":"#f6ad48"
                }
            ]
        ],
        answer:3,
    },
    {
        id:15,
        title:"チャイニーズレッド",
        subTitle:"あざやかな黄赤",
        colorCode:"#ea5520",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"チャイニーズレッド",
                    "colorCode":"#ea5520"
                },
                {
                    "name":"黄丹",
                    "colorCode":"#ee7948"
                },
                {
                    "name":"バーミリオン",
                    "colorCode":"#eb613b"
                }
            ],
            [
                {
                    "name":"チャイニーズレッド",
                    "colorCode":"#ea5520"
                },
                {
                    "name":"柑子色",
                    "colorCode":"#f6ad48"
                },
                {
                    "name":"桧皮色",
                    "colorCode":"#965036"
                }
            ],
            [
                {
                    "name":"チャイニーズレッド",
                    "colorCode":"#ea5520"
                },
                {
                    "name":"マリーゴールド",
                    "colorCode":"#f39800"
                },
                {
                    "name":"黄丹",
                    "colorCode":"#ee7948"
                },
            ]
        ],
        answer:1,
    },
    {
        id:16,
        title:"バーントシェンナ",
        subTitle:"くすんだ黄赤",
        colorCode:"#b25532",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"桧皮色",
                    "colorCode":"#965036"
                },
                {
                    "name":"バーントシェンナ",
                    "colorCode":"#b25532"
                },
                {
                    "name":"ローシェンナ",
                    "colorCode":"#d98032"
                }
            ],
            [
                {
                    "name":"タン",
                    "colorCode":"#c1813f"
                },
                {
                    "name":"バーントシェンナ",
                    "colorCode":"#b25532"
                },
                {
                    "name":"琥珀色",
                    "colorCode":"#bf7834"
                }
            ],
            [
                {
                    "name":"ローシェンナ",
                    "colorCode":"#d98032"
                },
                {
                    "name":"バーントシェンナ",
                    "colorCode":"#b25532"
                },
                {
                    "name":"タン",
                    "colorCode":"#c1813f"
                }
            ]
        ],
        answer:2,
    },
    {
        id:17,
        title:"ローシェンナ",
        subTitle:"つよい黄赤",
        colorCode:"#d98032",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"バーントシェンナ",
                    "colorCode":"#b25532"
                },
                {
                    "name":"ローシェンナ",
                    "colorCode":"#d98032"
                },
                {
                    "name":"タン",
                    "colorCode":"#c1813f"
                }
            ],
            [
                {
                    "name":"桧皮色",
                    "colorCode":"#965036"
                },
                {
                    "name":"ローシェンナ",
                    "colorCode":"#d98032"
                },
                {
                    "name":"琥珀色",
                    "colorCode":"#bf7834"
                }
            ],
            [
                {
                    "name":"テラコッタ",
                    "colorCode":"#be6d55"
                },
                {
                    "name":"ローシェンナ",
                    "colorCode":"#d98032"
                },
                {
                    "name":"ローアンバー",
                    "colorCode":"#916f24"
                }
            ]
        ],
        answer:3,
    },
    {
        id:18,
        title:"タン",
        subTitle:"くすんだ黄赤",
        colorCode:"#c1813f",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"カーキー",
                    "colorCode":"#bb9855"
                },
                {
                    "name":"ローシェンナ",
                    "colorCode":"#d98032"
                },
                {
                    "name":"タン",
                    "colorCode":"#c1813f"
                }
            ],
            [
                {
                    "name":"黄土色",
                    "colorCode":"#c39043"
                },
                {
                    "name":"ローシェンナ",
                    "colorCode":"#d98032"
                },
                {
                    "name":"タン",
                    "colorCode":"#c1813f"
                }
            ],
            [
                {
                    "name":"ローアンバー",
                    "colorCode":"#916f24"
                },
                {
                    "name":"アンバー",
                    "colorCode":"#c28953"
                },
                {
                    "name":"タン",
                    "colorCode":"#c1813f"
                }
            ]
        ],
        answer:3,
    },
    {
        id:19,
        title:"琥珀色",
        subTitle:"くすんだ赤みの黄",
        colorCode:"#bf7834",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"アンバー",
                    "colorCode":"#c28953"
                },
                {
                    "name":"琥珀色",
                    "colorCode":"#bf7834"
                },
                {
                    "name":"タン",
                    "colorCode":"#c1813f"
                }
            ],
            [
                {
                    "name":"ローシェンナ",
                    "colorCode":"#d98032"
                },
                {
                    "name":"琥珀色",
                    "colorCode":"#bf7834"
                },
                {
                    "name":"代赭",
                    "colorCode":"#bb541f"
                }
            ],
            [
                {
                    "name":"黄土色",
                    "colorCode":"#c39043"
                },
                {
                    "name":"琥珀色",
                    "colorCode":"#bf7834"
                },
                {
                    "name":"ローアンバー",
                    "colorCode":"#916f24"
                }
            ]
        ],
        answer:2,
    },
    {
        id:20,
        title:"朽葉色",
        subTitle:"灰みの赤みを帯びた黄",
        colorCode:"#917347",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"朽葉色",
                    "colorCode":"#917347"
                },
                {
                    "name":"カーキー",
                    "colorCode":"#bb9855"
                },
                {
                    "name":"タン",
                    "colorCode":"#c1813f"
                }
            ],
            [
                {
                    "name":"朽葉色",
                    "colorCode":"#917347"
                },
                {
                    "name":"ローシェンナ",
                    "colorCode":"#d98032"
                },
                {
                    "name":"桧皮色",
                    "colorCode":"#965036"
                }
            ],
            [
                {
                    "name":"朽葉色",
                    "colorCode":"#917347"
                },
                {
                    "name":"煤竹色",
                    "colorCode":"#6b5146"
                },
                {
                    "name":"代赭",
                    "colorCode":"#bb541f"
                }
            ]
        ],
        answer:1,
    },
    {
        id:21,
        title:"鬱金色",
        subTitle:"つよい黄",
        colorCode:"#fabf13",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"鬱金色",
                    "colorCode":"#fabf13"
                },
                {
                    "name":"刈安色",
                    "colorCode":"#f5e56b"
                },
                {
                    "name":"ゴールデンイエロー",
                    "colorCode":"#f8b856"
                }
            ],
            [
                {
                    "name":"鬱金色",
                    "colorCode":"#fabf13"
                },
                {
                    "name":"ネープルスイエロー",
                    "colorCode":"#fdd75c"
                },
                {
                    "name":"ジョンブリアン",
                    "colorCode":"#ffdc00"
                },
            ],
            [
                {
                    "name":"黄蘗色",
                    "colorCode":"#fef263"
                },
                {
                    "name":"レモンイエロー",
                    "colorCode":"#fff33f"
                },
                {
                    "name":"柑子色",
                    "colorCode":"#f6ad48"
                }
            ]
        ],
        answer:3,
    },
    {
        id:22,
        title:"刈安色",
        subTitle:"うすい緑みの黄",
        colorCode:"#f5e56b",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"黄蘗色",
                    "colorCode":"#fef263"
                },
                {
                    "name":"刈安色",
                    "colorCode":"#f5e56b"
                },
                {
                    "name":"カナリヤ",
                    "colorCode":"#fff262"
                }
            ],
            [
                {
                    "name":"ネープルスイエロー",
                    "colorCode":"#fdd75c"
                },
                {
                    "name":"刈安色",
                    "colorCode":"#f5e56b"
                },
                {
                    "name":"ゴールデンイエロー",
                    "colorCode":"#f8b856"
                }
            ],
            [
                {
                    "name":"レモンイエロー",
                    "colorCode":"#fff33f"
                },
                {
                    "name":"刈安色",
                    "colorCode":"#f5e56b"
                },
                {
                    "name":"鬱金色",
                    "colorCode":"#fabf13"
                }
            ]
        ],
        answer:3,
    },
    {
        id:23,
        title:"エクルベイジュ",
        subTitle:"うすい赤みの黄",
        colorCode:"#f8eacf",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"ピーチ",
                    "colorCode":"#fbd8b5"
                },
                {
                    "name":"ネープルスイエロー",
                    "colorCode":"#fdd75c"
                },
                {
                    "name":"エクルベイジュ",
                    "colorCode":"#f8eacf"
                }
            ],
            [
                {
                    "name":"生成り色",
                    "colorCode":"#fbfaf3"
                },
                {
                    "name":"アイボリー",
                    "colorCode":"#F8F5E4"
                },
                {
                    "name":"エクルベイジュ",
                    "colorCode":"#f8eacf"
                }
            ],
            [
                {
                    "name":"カナリヤ",
                    "colorCode":"#fff262"
                },
                {
                    "name":"生成り色",
                    "colorCode":"#fbfaf3"
                },
                {
                    "name":"エクルベイジュ",
                    "colorCode":"#f8eacf"
                }
            ]
        ],
        answer:3,
    },
    {
        id:24,
        title:"ゴールデンイエロー",
        subTitle:"つよい赤みの黄",
        colorCode:"#f8b856",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"刈安色",
                    "colorCode":"#f5e56b"
                },
                {
                    "name":"ゴールデンイエロー",
                    "colorCode":"#f8b856"
                },
                {
                    "name":"ネープルスイエロー",
                    "colorCode":"#fdd75c"
                }
            ],
            [
                {
                    "name":"ジョンブリアン",
                    "colorCode":"#ffdc00"
                },
                {
                    "name":"ゴールデンイエロー",
                    "colorCode":"#f8b856"
                },
                {
                    "name":"レモンイエロー",
                    "colorCode":"#fff33f"
                }
            ],
            [
                {
                    "name":"鬱金色",
                    "colorCode":"#fabf13"
                },
                {
                    "name":"ゴールデンイエロー",
                    "colorCode":"#f8b856"
                },
                {
                    "name":"柑子色",
                    "colorCode":"#f6ad48"
                }
            ]
        ],
        answer:2,
    },
    {
        id:25,
        title:"アンバー",
        subTitle:"くすんだ赤みの黄",
        colorCode:"#c28953",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"アンバー",
                    "colorCode":"#c28953"
                },
                {
                    "name":"ローシェンナ",
                    "colorCode":"#d98032"
                },
                {
                    "name":"黄土色",
                    "colorCode":"#c39043"
                }
            ],
            [
                {
                    "name":"アンバー",
                    "colorCode":"#c28953"
                },
                {
                    "name":"琥珀色",
                    "colorCode":"#bf7834"
                },
                {
                    "name":"タン",
                    "colorCode":"#c1813f"
                }
            ],
            [
                {
                    "name":"アンバー",
                    "colorCode":"#c28953"
                },
                {
                    "name":"バーントアンバー",
                    "colorCode":"#7a5e3d"
                },
                {
                    "name":"代赭",
                    "colorCode":"#bb541f"
                }
            ]
        ],
        answer:1,
    },
    {
        id:26,
        title:"バーントアンバー",
        subTitle:"ごく暗い赤みの黄",
        colorCode:"#7a5e3d",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"バーントアンバー",
                    "colorCode":"#7a5e3d"
                },
                {
                    "name":"桧皮色",
                    "colorCode":"#965036"
                },
                {
                    "name":"アンバー",
                    "colorCode":"#c28953"
                }
            ],
            [
                {
                    "name":"バーントアンバー",
                    "colorCode":"#7a5e3d"
                },
                {
                    "name":"ローシェンナ",
                    "colorCode":"#d98032"
                },
                {
                    "name":"テラコッタ",
                    "colorCode":"#be6d55"
                }
            ],
            [
                {
                    "name":"バーントアンバー",
                    "colorCode":"#7a5e3d"
                },
                {
                    "name":"琥珀色",
                    "colorCode":"#bf7834"
                },
                {
                    "name":"ローアンバー",
                    "colorCode":"#916f24"
                }
            ]
        ],
        answer:1,
    },
    {
        id:27,
        title:"ローアンバー",
        subTitle:"暗い黄",
        colorCode:"#916f24",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"タン",
                    "colorCode":"#c1813f"
                },
                {
                    "name":"ローアンバー",
                    "colorCode":"#916f24"
                },
                {
                    "name":"琥珀色",
                    "colorCode":"#bf7834"
                }
            ],
            [
                {
                    "name":"タン",
                    "colorCode":"#c1813f"
                },
                {
                    "name":"ローアンバー",
                    "colorCode":"#916f24"
                },
                {
                    "name":"バーントアンバー",
                    "colorCode":"#7a5e3d"
                }
            ],
            [
                {
                    "name":"ローシェンナ",
                    "colorCode":"#d98032"
                },
                {
                    "name":"ローアンバー",
                    "colorCode":"#916f24"
                },
                {
                    "name":"アンバー",
                    "colorCode":"#c28953"
                }
            ]
        ],
        answer:2,
    },
    {
        id:28,
        title:"ネープルスイエロー",
        subTitle:"つよい黄",
        colorCode:"#fdd75c",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"刈安色",
                    "colorCode":"#f5e56b"
                },
                {
                    "name":"カナリヤ",
                    "colorCode":"#fff262"
                },
                {
                    "name":"ネープルスイエロー",
                    "colorCode":"#fdd75c"
                }
            ],
            [
                {
                    "name":"ジョンブリアン",
                    "colorCode":"#ffdc00"
                },
                {
                    "name":"黄蘗色",
                    "colorCode":"#fef263"
                },
                {
                    "name":"ネープルスイエロー",
                    "colorCode":"#fdd75c"
                }
            ],
            [
                {
                    "name":"レモンイエロー",
                    "colorCode":"#fff33f"
                },
                {
                    "name":"ゴールデンイエロー",
                    "colorCode":"#f8b856"
                },
                {
                    "name":"ネープルスイエロー",
                    "colorCode":"#fdd75c"
                }
            ]
        ],
        answer:3,
    },
    {
        id:29,
        title:"ジョンブリアン",
        subTitle:"あざやかな黄",
        colorCode:"#ffdc00",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"カナリヤ",
                    "colorCode":"#fff262"
                },
                {
                    "name":"ジョンブリアン",
                    "colorCode":"#ffdc00"
                },
                {
                    "name":"鬱金色",
                    "colorCode":"#fabf13"
                }
            ],
            [
                {
                    "name":"ゴールデンイエロー",
                    "colorCode":"#f8b856"
                },
                {
                    "name":"ジョンブリアン",
                    "colorCode":"#ffdc00"
                },
                {
                    "name":"ネープルスイエロー",
                    "colorCode":"#fdd75c"
                }
            ],
            [
                {
                    "name":"レモンイエロー",
                    "colorCode":"#fff33f"
                },
                {
                    "name":"ジョンブリアン",
                    "colorCode":"#ffdc00"
                },
                {
                    "name":"ゴールデンイエロー",
                    "colorCode":"#f8b856"
                }
            ]
        ],
        answer:2,
    },
    {
        id:30,
        title:"黄蘗色",
        subTitle:"あかるい黄緑",
        colorCode:"#fef263",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"黄蘗色",
                    "colorCode":"#fef263"
                },
                {
                    "name":"ゴールデンイエロー",
                    "colorCode":"#f8b856"
                },
                {
                    "name":"カナリヤ",
                    "colorCode":"#fff262"
                }
            ],
            [
                {
                    "name":"黄蘗色",
                    "colorCode":"#fef263"
                },
                {
                    "name":"レモンイエロー",
                    "colorCode":"#fff33f"
                },
                {
                    "name":"ネープルスイエロー",
                    "colorCode":"#fdd75c"
                }
            ],
            [
                {
                    "name":"黄蘗色",
                    "colorCode":"#fef263"
                },
                {
                    "name":"柑子色",
                    "colorCode":"#f6ad48"
                },
                {
                    "name":"刈安色",
                    "colorCode":"#f5e56b"
                }
            ]
        ],
        answer:1,
    },
    {
        id:31,
        title:"海松色",
        subTitle:"暗い灰みの黄緑",
        colorCode:"#726d3f",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"鶸色",
                    "colorCode":"#d7cf3a"
                },
                {
                    "name":"グラスグリーン",
                    "colorCode":"#7b8d41"
                },
                {
                    "name":"海松色",
                    "colorCode":"#726d3f"
                }
            ],
            [
                {
                    "name":"鶯色",
                    "colorCode":"#9d973b"
                },
                {
                    "name":"グラスグリーン",
                    "colorCode":"#7b8d41"
                },
                {
                    "name":"海松色",
                    "colorCode":"#726d3f"
                }
            ],
            [
                {
                    "name":"オリーブ",
                    "colorCode":"#72640a"
                },
                {
                    "name":"鶯色",
                    "colorCode":"#9d973b"
                },
                {
                    "name":"海松色",
                    "colorCode":"#726d3f"
                }
            ]
        ],
        answer:3,
    },
    {
        id:32,
        title:"鶸色",
        subTitle:"つよい黄緑",
        colorCode:"#d7cf3a",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"鶸色",
                    "colorCode":"#d7cf3a"
                },
                {
                    "name":"海松色",
                    "colorCode":"#726d3f"
                },
                {
                    "name":"グラスグリーン",
                    "colorCode":"#7b8d41"
                }
            ],
            [
                {
                    "name":"鶸色",
                    "colorCode":"#d7cf3a"
                },
                {
                    "name":"鶯色",
                    "colorCode":"#9d973b"
                },
                {
                    "name":"海松色",
                    "colorCode":"#726d3f"
                }
            ],
            [
                {
                    "name":"鶸色",
                    "colorCode":"#d7cf3a"
                },
                {
                    "name":"鴇色",
                    "colorCode":"#f4b3c2"
                },
                {
                    "name":"鶯色",
                    "colorCode":"#9d973b"
                }
            ]
        ],
        answer:1,
    },
    {
        id:33,
        title:"シャトルーズグリーン",
        subTitle:"明るい黄緑",
        colorCode:"#d9e367",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"萌黄",
                    "colorCode":"#AFD147"
                },
                {
                    "name":"シャトルーズグリーン",
                    "colorCode":"#d9e367"
                },
                {
                    "name":"鶸色",
                    "colorCode":"#d7cf3a"
                }
            ],
            [
                {
                    "name":"グラスグリーン",
                    "colorCode":"#7b8d41"
                },
                {
                    "name":"シャトルーズグリーン",
                    "colorCode":"#d9e367"
                },
                {
                    "name":"リーフグリーン",
                    "colorCode":"#9dc04c"
                }
            ],
            [
                {
                    "name":"リーフグリーン",
                    "colorCode":"#9dc04c"
                },
                {
                    "name":"シャトルーズグリーン",
                    "colorCode":"#d9e367"
                },
                {
                    "name":"萌黄",
                    "colorCode":"#AFD147"
                }
            ]
        ],
        answer:2,
    },
    {
        id:34,
        title:"リーフグリーン",
        subTitle:"つよい黄緑",
        colorCode:"#9dc04c",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"リーフグリーン",
                    "colorCode":"#9dc04c"
                },
                {
                    "name":"シャトルーズグリーン",
                    "colorCode":"#d9e367"
                },
                {
                    "name":"グラスグリーン",
                    "colorCode":"#7b8d41"
                }
            ],
            [
                {
                    "name":"リーフグリーン",
                    "colorCode":"#9dc04c"
                },
                {
                    "name":"鶯色",
                    "colorCode":"#9d973b"
                },
                {
                    "name":"鶸色",
                    "colorCode":"#d7cf3a"
                }
            ],
            [
                {
                    "name":"リーフグリーン",
                    "colorCode":"#9dc04c"
                },
                {
                    "name":"萌黄",
                    "colorCode":"#AFD147"
                },
                {
                    "name":"オリーブ",
                    "colorCode":"#72640a"
                }
            ]
        ],
        answer:1,
    },
    {
        id:35,
        title:"グラスグリーン",
        subTitle:"くすんだ黄緑",
        colorCode:"#7b8d41",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"リーフグリーン",
                    "colorCode":"#9dc04c"
                },
                {
                    "name":"海松色",
                    "colorCode":"#726d3f"
                },
                {
                    "name":"グラスグリーン",
                    "colorCode":"#7b8d41"
                }
            ],
            [
                {
                    "name":"鶸色",
                    "colorCode":"#d7cf3a"
                },
                {
                    "name":"鶯色",
                    "colorCode":"#9d973b"
                },
                {
                    "name":"グラスグリーン",
                    "colorCode":"#7b8d41"
                }
            ],
            [
                {
                    "name":"オリーブ",
                    "colorCode":"#72640a"
                },
                {
                    "name":"シャトルーズグリーン",
                    "colorCode":"#d9e367"
                },
                {
                    "name":"グラスグリーン",
                    "colorCode":"#7b8d41"
                }
            ]
        ],
        answer:3,
    },
    {
        id:36,
        title:"常磐色",
        subTitle:"こい緑",
        colorCode:"#007c45",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"常磐色",
                    "colorCode":"#007c45"
                },
                {
                    "name":"ボトルグリーン",
                    "colorCode":"#005635"
                },
                {
                    "name":"グラスグリーン",
                    "colorCode":"#7b8d41"
                }
            ],
            [
                {
                    "name":"常磐色",
                    "colorCode":"#007c45"
                },
                {
                    "name":"マラカイトグリーン",
                    "colorCode":"##009854"
                },
                {
                    "name":"オリーブ",
                    "colorCode":"#72640a"
                }
            ],
            [
                {
                    "name":"常磐色",
                    "colorCode":"#007c45"
                },
                {
                    "name":"海松色",
                    "colorCode":"#726d3f"
                },
                {
                    "name":"ボトルグリーン",
                    "colorCode":"#005635"
                }
            ]
        ],
        answer:1,
    },
    {
        id:37,
        title:"緑青色",
        subTitle:"くすんだ緑",
        colorCode:"#4f8a5d",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"鶯色",
                    "colorCode":"#9d973b"
                },
                {
                    "name":"緑青色",
                    "colorCode":"#4f8a5d"
                },
                {
                    "name":"常磐色",
                    "colorCode":"#007c45"
                }
            ],
            [
                {
                    "name":"コバルトグリーン",
                    "colorCode":"#3ab483"
                },
                {
                    "name":"緑青色",
                    "colorCode":"#4f8a5d"
                },
                {
                    "name":"ミントグリーン",
                    "colorCode":"#98ce97"
                }
            ],
            [
                {
                    "name":"ピーコックグリーン",
                    "colorCode":"#00a496"
                },
                {
                    "name":"緑青色",
                    "colorCode":"#4f8a5d"
                },
                {
                    "name":"青磁色",
                    "colorCode":"#68b7a1"
                }
            ]
        ],
        answer:2,
    },
    {
        id:38,
        title:"アップルグリーン",
        subTitle:"やわらかい黄みの緑",
        colorCode:"#a2cc89",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"コバルトグリーン",
                    "colorCode":"#3ab483"
                },
                {
                    "name":"シャトルーズグリーン",
                    "colorCode":"#d9e367"
                },
                {
                    "name":"アップルグリーン",
                    "colorCode":"#a2cc89"
                }
            ],
            [
                {
                    "name":"ピーコックグリーン",
                    "colorCode":"#00a496"
                },
                {
                    "name":"ミントグリーン",
                    "colorCode":"#98ce97"
                },
                {
                    "name":"アップルグリーン",
                    "colorCode":"#a2cc89"
                }
            ],
            [
                {
                    "name":"ミントグリーン",
                    "colorCode":"#98ce97"
                },
                {
                    "name":"グラスグリーン",
                    "colorCode":"#7b8d41"
                },
                {
                    "name":"アップルグリーン",
                    "colorCode":"#a2cc89"
                }
            ]
        ],
        answer:3,
    },
    {
        id:39,
        title:"ミントグリーン",
        subTitle:"明るい緑",
        colorCode:"#98ce97",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"ミントグリーン",
                    "colorCode":"#98ce97"
                },
                {
                    "name":"アップルグリーン",
                    "colorCode":"#a2cc89"
                },
                {
                    "name":"シャトルーズグリーン",
                    "colorCode":"#d9e367"
                }
            ],
            [
                {
                    "name":"ミントグリーン",
                    "colorCode":"#98ce97"
                },
                {
                    "name":"リーフグリーン",
                    "colorCode":"#9dc04c"
                },
                {
                    "name":"ピーコックグリーン",
                    "colorCode":"#00a496"
                }
            ],
            [
                {
                    "name":"ミントグリーン",
                    "colorCode":"#98ce97"
                },
                {
                    "name":"緑青色",
                    "colorCode":"#4f8a5d"
                },
                {
                    "name":"アップルグリーン",
                    "colorCode":"#a2cc89"
                }
            ]
        ],
        answer:1,
    },
    {
        id:40,
        title:"マラカイトグリーン",
        subTitle:"こい緑",
        colorCode:"#009854",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"ピーコックグリーン",
                    "colorCode":"#00a496"
                },
                {
                    "name":"エメラルドグリーン",
                    "colorCode":"#00aa6e"
                },
                {
                    "name":"マラカイトグリーン",
                    "colorCode":"##009854"
                }
            ],
            [
                {
                    "name":"ピーコックグリーン",
                    "colorCode":"#00a496"
                },
                {
                    "name":"コバルトグリーン",
                    "colorCode":"#3ab483"
                },
                {
                    "name":"マラカイトグリーン",
                    "colorCode":"##009854"
                }
            ],
            [
                {
                    "name":"ボトルグリーン",
                    "colorCode":"#005635"
                },
                {
                    "name":"常磐色",
                    "colorCode":"#007c45"
                },
                {
                    "name":"マラカイトグリーン",
                    "colorCode":"##009854"
                }
            ]
        ],
        answer:3,
    },
    {
        id:41,
        title:"ボトルグリーン",
        subTitle:"ごく暗い緑",
        colorCode:"#005635",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"ボトルグリーン",
                    "colorCode":"#005635"
                },
                {
                    "name":"エメラルドグリーン",
                    "colorCode":"#00aa6e"
                },
                {
                    "name":"常磐色",
                    "colorCode":"#007c45"
                }
            ],
            [
                {
                    "name":"ボトルグリーン",
                    "colorCode":"#005635"
                },
                {
                    "name":"マラカイトグリーン",
                    "colorCode":"##009854"
                },
                {
                    "name":"海松色",
                    "colorCode":"#726d3f"
                }
            ],
            [
                {
                    "name":"ボトルグリーン",
                    "colorCode":"#005635"
                },
                {
                    "name":"常磐色",
                    "colorCode":"#007c45"
                },
                {
                    "name":"鉄色",
                    "colorCode":"#005242"
                }
            ]
        ],
        answer:1,
    },
    {
        id:42,
        title:"鉄色",
        subTitle:"ごく暗い青緑",
        colorCode:"#005242",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"ボトルグリーン",
                    "colorCode":"#005635"
                },
                {
                    "name":"鉄色",
                    "colorCode":"#005242"
                },
                {
                    "name":"常磐色",
                    "colorCode":"#007c45"
                }
            ],
            [
                {
                    "name":"青磁色",
                    "colorCode":"#68b7a1"
                },
                {
                    "name":"鉄色",
                    "colorCode":"#005242"
                },
                {
                    "name":"エメラルドグリーン",
                    "colorCode":"#00aa6e"
                }
            ],
            [
                {
                    "name":"常磐色",
                    "colorCode":"#007c45"
                },
                {
                    "name":"鉄色",
                    "colorCode":"#005242"
                },
                {
                    "name":"海松色",
                    "colorCode":"#726d3f"
                }
            ]
        ],
        answer:2,
    },
    {
        id:43,
        title:"ピーコックグリーン",
        subTitle:"青緑",
        colorCode:"#00a496",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"ピーコックグリーン",
                    "colorCode":"#00a496"
                },
                {
                    "name":"ナイルブルー",
                    "colorCode":"#259f94"
                },
                {
                    "name":"浅葱色",
                    "colorCode":"#00a1ae"
                }
            ],
            [
                {
                    "name":"ピーコックグリーン",
                    "colorCode":"#00a496"
                },
                {
                    "name":"新橋色",
                    "colorCode":"#64bcc7"
                },
                {
                    "name":"群青色",
                    "colorCode":"#4e67b0"
                }
            ],
            [
                {
                    "name":"ピーコックグリーン",
                    "colorCode":"#00a496"
                },
                {
                    "name":"セルリアンブルー",
                    "colorCode":"#008db7"
                },
                {
                    "name":"サックスブルー",
                    "colorCode":"#3a8daa"
                }
            ]
        ],
        answer:1,
    },
    {
        id:44,
        title:"ナイルブルー",
        subTitle:"くすんだ青緑",
        colorCode:"#259f94",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"セルリアンブルー",
                    "colorCode":"#008db7"
                },
                {
                    "name":"青磁色",
                    "colorCode":"#68b7a1"
                },
                {
                    "name":"ナイルブルー",
                    "colorCode":"#259f94"
                }
            ],
            [
                {
                    "name":"浅葱色",
                    "colorCode":"#00a1ae"
                },
                {
                    "name":"セルリアンブルー",
                    "colorCode":"#008db7"
                },
                {
                    "name":"ナイルブルー",
                    "colorCode":"#259f94"
                }
            ],
            [
                {
                    "name":"群青色",
                    "colorCode":"#4e67b0"
                },
                {
                    "name":"サックスブルー",
                    "colorCode":"#3a8daa"
                },
                {
                    "name":"ナイルブルー",
                    "colorCode":"#259f94"
                }
            ]
        ],
        answer:3,
    },
    {
        id:45,
        title:"新橋色",
        subTitle:"明るい緑みの青",
        colorCode:"#64bcc7",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"空色",
                    "colorCode":"#A0D8EF"
                },
                {
                    "name":"セルリアンブルー",
                    "colorCode":"#008db7"
                },
                {
                    "name":"新橋色",
                    "colorCode":"#64bcc7"
                }
            ],
            [
                {
                    "name":"浅葱色",
                    "colorCode":"#00a1ae"
                },
                {
                    "name":"甕覗",
                    "colorCode":"#a2d7dd"
                },
                {
                    "name":"新橋色",
                    "colorCode":"#64bcc7"
                }
            ],
            [
                {
                    "name":"甕覗",
                    "colorCode":"#a2d7dd"
                },
                {
                    "name":"浅葱色",
                    "colorCode":"#00a1ae"
                },
                {
                    "name":"新橋色",
                    "colorCode":"#64bcc7"
                }
            ]
        ],
        answer:3,
    },
    {
        id:46,
        title:"納戸色",
        subTitle:"つよい緑みの青",
        colorCode:"#007d92",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"ナイルブルー",
                    "colorCode":"#259f94"
                },
                {
                    "name":"納戸色",
                    "colorCode":"#007d92"
                },
                {
                    "name":"青磁色",
                    "colorCode":"#68b7a1"
                }
            ],
            [
                {
                    "name":"サックスブルー",
                    "colorCode":"#3a8daa"
                },
                {
                    "name":"納戸色",
                    "colorCode":"#007d92"
                },
                {
                    "name":"縹色",
                    "colorCode":"#2980af"
                }
            ],
            [
                {
                    "name":"セルリアンブルー",
                    "colorCode":"#008db7"
                },
                {
                    "name":"納戸色",
                    "colorCode":"#007d92"
                },
                {
                    "name":"群青色",
                    "colorCode":"#4e67b0"
                }
            ]
        ],
        answer:2,
    },
    {
        id:47,
        title:"甕覗",
        subTitle:"やわらかい緑みの青",
        colorCode:"#a2d7dd",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"甕覗",
                    "colorCode":"#a2d7dd"
                },
                {
                    "name":"新橋色",
                    "colorCode":"#64bcc7"
                },
                {
                    "name":"セルリアンブルー",
                    "colorCode":"#008db7"
                }
            ],
            [
                {
                    "name":"甕覗",
                    "colorCode":"#a2d7dd"
                },
                {
                    "name":"縹色",
                    "colorCode":"#2980af"
                },
                {
                    "name":"新橋色",
                    "colorCode":"#64bcc7"
                }
            ],
            [
                {
                    "name":"甕覗",
                    "colorCode":"#a2d7dd"
                },
                {
                    "name":"浅葱色",
                    "colorCode":"#00a1ae"
                },
                {
                    "name":"青磁色",
                    "colorCode":"#68b7a1"
                }
            ]
        ],
        answer:1,
    },
    {
        id:48,
        title:"縹色",
        subTitle:"つよい青",
        colorCode:"#2980af",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"藍色",
                    "colorCode":"#0f5779"
                },
                {
                    "name":"群青色",
                    "colorCode":"#4e67b0"
                },
                {
                    "name":"縹色",
                    "colorCode":"#2980af"
                }
            ],
            [
                {
                    "name":"マリンブルー",
                    "colorCode":"#006788"
                },
                {
                    "name":"納戸色",
                    "colorCode":"#007d92"
                },
                {
                    "name":"縹色",
                    "colorCode":"#2980af"
                }
            ],
            [
                {
                    "name":"コバルトブルー",
                    "colorCode":"#0068b7"
                },
                {
                    "name":"ナイルブルー",
                    "colorCode":"#259f94"
                },
                {
                    "name":"縹色",
                    "colorCode":"#2980af"
                }
            ]
        ],
        answer:3,
    },
    {
        id:49,
        title:"セルリアンブルー",
        subTitle:"あざやかな青",
        colorCode:"#008db7",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"ナイルブルー",
                    "colorCode":"#259f94"
                },
                {
                    "name":"セルリアンブルー",
                    "colorCode":"#008db7"
                },
                {
                    "name":"縹色",
                    "colorCode":"#2980af"
                }
            ],
            [
                {
                    "name":"納戸色",
                    "colorCode":"#007d92"
                },
                {
                    "name":"セルリアンブルー",
                    "colorCode":"#008db7"
                },
                {
                    "name":"コバルトブルー",
                    "colorCode":"#0068b7"
                }
            ],
            [
                {
                    "name":"縹色",
                    "colorCode":"#2980af"
                },
                {
                    "name":"セルリアンブルー",
                    "colorCode":"#008db7"
                },
                {
                    "name":"マリンブルー",
                    "colorCode":"#006788"
                }
            ]
        ],
        answer:2,
    },
    {
        id:50,
        title:"ミッドナイトブルー",
        subTitle:"ごく暗い紫みの青",
        colorCode:"#001d42",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"ミッドナイトブルー",
                    "colorCode":"#001d42"
                },
                {
                    "name":"瑠璃色",
                    "colorCode":"#1d50a2"
                },
                {
                    "name":"ネービーブルー",
                    "colorCode":"#1f2e55"
                }
            ],
            [
                {
                    "name":"ミッドナイトブルー",
                    "colorCode":"#001d42"
                },
                {
                    "name":"藍色",
                    "colorCode":"#0f5779"
                },
                {
                    "name":"縹色",
                    "colorCode":"#2980af"
                }
            ],
            [
                {
                    "name":"ミッドナイトブルー",
                    "colorCode":"#001d42"
                },
                {
                    "name":"ネービーブルー",
                    "colorCode":"#1f2e55"
                },
                {
                    "name":"納戸色",
                    "colorCode":"#007d92"
                }
            ]
        ],
        answer:1,
    },
    {
        id:51,
        title:"藤色",
        subTitle:"明るい青紫",
        colorCode:"#bbb7da",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"ライラック",
                    "colorCode":"#D2BADA"
                },
                {
                    "name":"バイオレット",
                    "colorCode":"#714f9d"
                },
                {
                    "name":"藤色",
                    "colorCode":"#bbb7da"
                }
            ],
            [
                {
                    "name":"ウィスタリア",
                    "colorCode":"#8e8bc2"
                },
                {
                    "name":"ラベンダー",
                    "colorCode":"#C4B3D3"
                },
                {
                    "name":"藤色",
                    "colorCode":"#bbb7da"
                }
            ],
            [
                {
                    "name":"ライラック",
                    "colorCode":"#D2BADA"
                },
                {
                    "name":"ウィスタリア",
                    "colorCode":"#8e8bc2"
                },
                {
                    "name":"藤色",
                    "colorCode":"#bbb7da"
                }
            ]
        ],
        answer:3,
    },
    {
        id:52,
        title:"ウィスタリア",
        subTitle:"あざやかな青紫",
        colorCode:"#8e8bc2",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"ラベンダー",
                    "colorCode":"#C4B3D3"
                },
                {
                    "name":"ウィスタリア",
                    "colorCode":"#8e8bc2"
                },
                {
                    "name":"ライラック",
                    "colorCode":"#D2BADA"
                }
            ],
            [
                {
                    "name":"藤色",
                    "colorCode":"#bbb7da"
                },
                {
                    "name":"ウィスタリア",
                    "colorCode":"#8e8bc2"
                },
                {
                    "name":"ライラック",
                    "colorCode":"#D2BADA"
                }
            ],
            [
                {
                    "name":"藤色",
                    "colorCode":"#bbb7da"
                },
                {
                    "name":"ウィスタリア",
                    "colorCode":"#8e8bc2"
                },
                {
                    "name":"バイオレット",
                    "colorCode":"#714f9d"
                }
            ]
        ],
        answer:2,
    },
    {
        id:53,
        title:"江戸紫",
        subTitle:"こい青みの紫",
        colorCode:"#734e95",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"茄子紺",
                    "colorCode":"#4b1a47"
                },
                {
                    "name":"バイオレット",
                    "colorCode":"#714f9d"
                },
                {
                    "name":"江戸紫",
                    "colorCode":"#734e95"
                }
            ],
            [
                {
                    "name":"古代紫",
                    "colorCode":"#895687"
                },
                {
                    "name":"桔梗色",
                    "colorCode":"#5754A3"
                },
                {
                    "name":"江戸紫",
                    "colorCode":"#734e95"
                }
            ],
            [
                {
                    "name":"藤色",
                    "colorCode":"#bbb7da"
                },
                {
                    "name":"古代紫",
                    "colorCode":"#895687"
                },
                {
                    "name":"江戸紫",
                    "colorCode":"#734e95"
                }
            ]
        ],
        answer:3,
    },
    {
        id:54,
        title:"古代紫",
        subTitle:"くすんだ紫",
        colorCode:"#895687",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"江戸紫",
                    "colorCode":"#734e95"
                },
                {
                    "name":"古代紫",
                    "colorCode":"#895687"
                },
                {
                    "name":"藤色",
                    "colorCode":"#bbb7da"
                }
            ],
            [
                {
                    "name":"茄子紺",
                    "colorCode":"#4b1a47"
                },
                {
                    "name":"古代紫",
                    "colorCode":"#895687"
                },
                {
                    "name":"バイオレット",
                    "colorCode":"#714f9d"
                }
            ],
            [
                {
                    "name":"桔梗色",
                    "colorCode":"#5754A3"
                },
                {
                    "name":"古代紫",
                    "colorCode":"#895687"
                },
                {
                    "name":"江戸紫",
                    "colorCode":"#734e95"
                }
            ]
        ],
        answer:2,
    },
    {
        id:55,
        title:"ライラック",
        subTitle:"やわらかい紫",
        colorCode:"#D2BADA",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"ライラック",
                    "colorCode":"#D2BADA"
                },
                {
                    "name":"ラベンダー",
                    "colorCode":"#C4B3D3"
                },
                {
                    "name":"ウィスタリア",
                    "colorCode":"#8e8bc2"
                }
            ],
            [
                {
                    "name":"ライラック",
                    "colorCode":"#D2BADA"
                },
                {
                    "name":"藤色",
                    "colorCode":"#bbb7da"
                },
                {
                    "name":"ラベンダー",
                    "colorCode":"#C4B3D3"
                }
            ],
            [
                {
                    "name":"ライラック",
                    "colorCode":"#D2BADA"
                },
                {
                    "name":"ウィスタリア",
                    "colorCode":"#8e8bc2"
                },
                {
                    "name":"藤色",
                    "colorCode":"#bbb7da"
                }
            ]
        ],
        answer:1,
    },
    {
        id:56,
        title:"銀鼠",
        subTitle:"明るい灰色",
        colorCode:"#afafb0",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"シルバーグレイ",
                    "colorCode":"#afafb0"
                },
                {
                    "name":"利休鼠",
                    "colorCode":"#7b8174"
                },
                {
                    "name":"銀鼠",
                    "colorCode":"#afafb0"
                }
            ],
            [
                {
                    "name":"スレートグレイ",
                    "colorCode":"#636062"
                },
                {
                    "name":"シルバーグレイ",
                    "colorCode":"#afafb0"
                },
                {
                    "name":"銀鼠",
                    "colorCode":"#afafb0"
                }
            ],
            [
                {
                    "name":"利休鼠",
                    "colorCode":"#7b8174"
                },
                {
                    "name":"茶鼠",
                    "colorCode":"#a99e93"
                },
                {
                    "name":"銀鼠",
                    "colorCode":"#afafb0"
                }
            ]
        ],
        answer:3,
    },
    {
        id:57,
        title:"茶鼠",
        subTitle:"黄赤みの灰色",
        colorCode:"#a99e93",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"銀鼠",
                    "colorCode":"#afafb0"
                },
                {
                    "name":"茶鼠",
                    "colorCode":"#a99e93"
                },
                {
                    "name":"利休鼠",
                    "colorCode":"#7b8174"
                }
            ],
            [
                {
                    "name":"煤竹色",
                    "colorCode":"#6b5146"
                },
                {
                    "name":"茶鼠",
                    "colorCode":"#a99e93"
                },
                {
                    "name":"朽葉色",
                    "colorCode":"#917347"
                }
            ],
            [
                {
                    "name":"蘇芳",
                    "colorCode":"#9e3d3e"
                },
                {
                    "name":"茶鼠",
                    "colorCode":"#a99e93"
                },
                {
                    "name":"煤竹色",
                    "colorCode":"#6b5146"
                }
            ]
        ],
        answer:2,
    },
    {
        id:58,
        title:"利休鼠",
        subTitle:"緑みの灰色",
        colorCode:"#7b8174",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"鶯色",
                    "colorCode":"#9d973b"
                },
                {
                    "name":"銀鼠",
                    "colorCode":"#afafb0"
                },
                {
                    "name":"利休鼠",
                    "colorCode":"#7b8174"
                }
            ],
            [
                {
                    "name":"鶸色",
                    "colorCode":"#d7cf3a"
                },
                {
                    "name":"煤竹色",
                    "colorCode":"#6b5146"
                },
                {
                    "name":"利休鼠",
                    "colorCode":"#7b8174"
                }
            ],
            [
                {
                    "name":"茶鼠",
                    "colorCode":"#a99e93"
                },
                {
                    "name":"銀鼠",
                    "colorCode":"#afafb0"
                },
                {
                    "name":"利休鼠",
                    "colorCode":"#7b8174"
                }
            ]
        ],
        answer:3,
    },
    {
        id:59,
        title:"煤竹色",
        subTitle:"赤みを帯びた黄みの暗い灰色",
        colorCode:"#6b5146",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"朽葉色",
                    "colorCode":"#917347"
                },
                {
                    "name":"煤竹色",
                    "colorCode":"#6b5146"
                },
                {
                    "name":"茶鼠",
                    "colorCode":"#a99e93"
                }
            ],
            [
                {
                    "name":"利休鼠",
                    "colorCode":"#7b8174"
                },
                {
                    "name":"煤竹色",
                    "colorCode":"#6b5146"
                },
                {
                    "name":"スレートグレイ",
                    "colorCode":"#636062"
                }
            ],
            [
                {
                    "name":"銀鼠",
                    "colorCode":"#afafb0"
                },
                {
                    "name":"煤竹色",
                    "colorCode":"#6b5146"
                },
                {
                    "name":"朽葉色",
                    "colorCode":"#917347"
                }
            ]
        ],
        answer:2,
    },
    {
        id:60,
        title:"スレートグレイ",
        subTitle:"暗い灰色",
        colorCode:"#636062",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"スレートグレイ",
                    "colorCode":"#636062"
                },
                {
                    "name":"チャコールグレイ",
                    "colorCode":"#4e4449"
                },
                {
                    "name":"茶鼠",
                    "colorCode":"#a99e93"
                }
            ],
            [
                {
                    "name":"スレートグレイ",
                    "colorCode":"#636062"
                },
                {
                    "name":"銀鼠",
                    "colorCode":"#afafb0"
                },
                {
                    "name":"チャコールグレイ",
                    "colorCode":"#4e4449"
                }
            ],
            [
                {
                    "name":"スレートグレイ",
                    "colorCode":"#636062"
                },
                {
                    "name":"チャコールグレイ",
                    "colorCode":"#4e4449"
                },
                {
                    "name":"シルバーグレイ",
                    "colorCode":"#afafb0"
                }
            ]
        ],
        answer:1,
    },
    {
        id:61,
        title:"ランプブラック",
        subTitle:"黒",
        colorCode:"#24130d",
        description:"テキストが入ります",
        choices:[
            [
                {
                    "name":"ランプブラック",
                    "colorCode":"#24130d"
                },
                {
                    "name":"ミッドナイトブルー",
                    "colorCode":"#001d42"
                },
                {
                    "name":"スレートグレイ",
                    "colorCode":"#636062"
                }
            ],
            [
                {
                    "name":"ランプブラック",
                    "colorCode":"#24130d"
                },
                {
                    "name":"チャコールグレイ",
                    "colorCode":"#4e4449"
                },
                {
                    "name":"ミッドナイトブルー",
                    "colorCode":"#001d42"
                }
            ],
            [
                {
                    "name":"ランプブラック",
                    "colorCode":"#24130d"
                },
                {
                    "name":"煤竹色",
                    "colorCode":"#6b5146"
                },
                {
                    "name":"茄子紺",
                    "colorCode":"#4b1a47"
                }
            ]
        ],
        answer:1,
    },
];

