/***
 * 診断の質問リスト
 * @type {[{subTitle: string, answer: number, description: string, colorCode: string, id: number, title: string, choices: string[][], faultCount: number}]}
 */
export const thirdExam = [
    {
        id:1,
        title:"鴇色（ときいろ）",
        subTitle:"明るい紫みの赤",
        colorCode:"#f4b3c2",
        description:"テキストが入ります",
        choices:[
            ["黒","白","赤"],
            ["ピンク","オレンジ","緑"],
            ["ゴールド","シルバー","白"],
        ],
        answer:1,
        faultCount:0,
    },
    {
        id:2,
        title:"韓紅色（からくれないいろ）",
        subTitle:"あざやかな赤",
        colorCode:"#e95464",
        description:"テキストが入ります",
        choices:[
            ["黒","白","赤"],
            ["ピンク","オレンジ","緑"],
            ["ゴールド","シルバー","白"],
        ],
        answer:3,
        faultCount:0,
    },
    {
        id:3,
        title:"蘇芳（すおう）",
        subTitle:"くすんだ赤",
        colorCode:"#9e3d3e",
        description:"テキストが入ります",
        choices:[
            ["黒","白","赤"],
            ["ピンク","オレンジ","緑"],
            ["ゴールド","シルバー","白"],
        ],
        answer:3,
        faultCount:0,
    },
    {
        id:4,
        title:"鳶色（とびいろ）",
        subTitle:"暗い黄みの赤",
        colorCode:"#8b4239",
        description:"テキストが入ります",
        choices:[
            ["黒","白","赤"],
            ["ピンク","オレンジ","緑"],
            ["ゴールド","シルバー","白"],
        ],
        answer:3,
        faultCount:0,
    },
];

